require: rubocop-bridgetown
inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - exe/**/*
    - benchmark/**/*
    - node_modules/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/tasks/*
    - test/**/*
    - db/**/*
    - config/**/*
    - rb2js.config.rb
    - "**/*.js.rb" # doesn't work :(

Style/Lambda:
  EnforcedStyle: literal

# minor changes to aid in Ruby2JS files:
Style/RedundantSelf:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
