require: rubocop-bridgetown
inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  Exclude:
    - bin/**/*
    - exe/**/*
    - benchmark/**/*
    - node_modules/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/tasks/*
    - test/**/*
    - db/**/*
    - config/**/*
    - rb2js.config.rb
    - "**/*.js.rb"

Style/Lambda:
  EnforcedStyle: literal
