# This file doesn't really do anything, other than force Solargraph's usage
# of Rubocop when autoformatting files to adhere to Standard's linting rules

#require:
#  - standard

#inherit_gem:
#  standard: config/base.yml

#Standard/SemanticBlocks:
#  Enabled: false


#require: rubocop-bridgetown
#inherit_gem:
#  rubocop-bridgetown: .rubocop.yml

require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

  Exclude:
    - "config.ru"
    - "Rakefile"
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/IndentationWidth:
  Severity: error
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/EmptyComment:
  Enabled: false
Layout/EndAlignment:
  Severity: error
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/UnreachableCode:
  Severity: error
Metrics/AbcSize:
  Max: 21
Metrics/ClassLength:
  Max: 240
Layout/LineLength:
  Max: 100
  Severity: warning
Metrics/MethodLength:
  CountComments: false
  Max: 20
  Severity: error
Metrics/ModuleLength:
  Max: 240
Metrics/ParameterLists:
  Max: 4
Metrics/PerceivedComplexity:
  Max: 8
Naming/FileName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/AndOr:
  Severity: error
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax: # This now adheres to GitHub's newest Ruby style guide
  EnforcedStyle: ruby19
  SupportedStyles:
    # checks for 1.9 syntax (e.g. {a: 1}) for all symbol keys
    - ruby19
    # checks for hash rocket syntax for all hashes
    - hash_rockets
    # forbids mixed key syntaxes (e.g. {a: 1, :b => 2})
    - no_mixed_keys
    # enforces both ruby19 and no_mixed_keys styles
    - ruby19_no_mixed_keys
  # Force hashes that have a symbol value to use hash rockets
  UseHashRocketsWithSymbolValues: false
  # Do not suggest { a?: 1 } over { :a? => 1 } in ruby19 style
  PreferHashRocketsForNonAlnumEndingSymbols: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineTernaryOperator:
  Severity: error
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%q": "{}"
    "%Q": "{}"
    "%r": "!!"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/RescueModifier:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
